/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.LamBaiDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import model.CauHoi;

/**
 *
 * @author CT030408
 */
public class LamBai extends javax.swing.JFrame implements Runnable, ActionListener {

    /**
     * Creates new form LamBai
     */
    private ArrayList list = new LamBaiDAO().taiCauHoi();
    private int tangGiam = 0;
    private String chon[] = new String[list.size()];
    private String chonDapAn[] = new String[list.size()];
    private String maCauhoi[] = new String[list.size()];
    private String maMon[] = new String[list.size()];
    private DefaultListModel listModel = new DefaultListModel();

    private static int tic = 0;
    private static int sec = 0;
    private static int min = 0;
    private static Thread runTimer;

    public LamBai() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle(new LamBaiDAO().docFile() + new LamBaiDAO().docFile2());
        btnGui.addActionListener(this);
        {
            runTimer = new Thread(this);
            runTimer.start();
        }
        for (int i = 0; i < list.size(); i++) {
            listModel.addElement(i + 1 + " -   ");
        }
        jList.setModel(listModel);
        lamBai();
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource().equals(btnGui)) {
            gui();
        }
    }

    public void gui() {
        new LamBaiDAO().ghiFile(maMon, maCauhoi, chonDapAn);
        new KetQua().setVisible(true);
        this.dispose();
    }

    @Override
    public void run() {
        try {

            while (true) {
                tic++;
                if (tic == 60) {
                    sec += 1;
                    tic = 0;
                }
                if (sec == 60) {
                    min += 1;
                    sec = 0;
                }
                if (tic <= 9) {
                    txttic.setText("0" + String.valueOf(tic));
                }
                if (tic <= 99 && tic >= 10) {
                    txttic.setText(String.valueOf(tic));
                }
                if (sec <= 9) {
                    txtsec.setText("0" + String.valueOf(sec));
                }
                if (sec <= 99 && sec >= 10) {
                    txtsec.setText(String.valueOf(sec));
                }
                if (min <= 9) {
                    txtmin.setText("0" + String.valueOf(min));
                }
                if (min <= 99 && min >= 10) {
                    txtmin.setText(String.valueOf(min));
                }
                Thread.sleep(10);
                if (min == (list.size())) {
                    gui();
                    break;
                }
            }
        } catch (Exception e) {
        }
    }

    public void lamBai() {
        {
            for (int i = 0; i < list.size(); i++) {
                if (jList.isSelectedIndex(i)) {
                    tangGiam = i;
                }
            }
        }
        buttonGroup1.clearSelection();
        {
            btnTruoc.setEnabled(true);
            btnTiep.setEnabled(true);
            if (tangGiam == 0) {
                btnTruoc.setEnabled(false);
            }
            if (tangGiam == list.size()-1) {
                btnTiep.setEnabled(false);
            }
        }
        {
            CauHoi ch = (CauHoi) list.get(tangGiam);
            maMon[tangGiam] = ch.getMaMon();
            maCauhoi[tangGiam] = ch.getMaCauHoi();
            txtCauSoMay.setText(Integer.toString(tangGiam + 1));
            txtCauHoi.setText(ch.getCauHoi());
            txtA.setText(ch.getA());
            txtB.setText(ch.getB());
            txtC.setText(ch.getC());
            txtD.setText(ch.getD());

        }
        {
            if (null != chon[tangGiam]) {
                if (chon[tangGiam].equals(tangGiam + 1 + " - A")) {
                    btnA.setSelected(true);
                } else if (chon[tangGiam].equals(tangGiam + 1 + " - B")) {
                    btnB.setSelected(true);
                } else if (chon[tangGiam].equals(tangGiam + 1 + " - C")) {
                    btnC.setSelected(true);
                } else {
                    btnD.setSelected(true);
                }
            }
        }
        jList.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCauSoMay = new javax.swing.JLabel();
        txtCauHoi = new javax.swing.JLabel();
        btnA = new javax.swing.JRadioButton();
        btnB = new javax.swing.JRadioButton();
        btnC = new javax.swing.JRadioButton();
        btnD = new javax.swing.JRadioButton();
        txtA = new javax.swing.JLabel();
        txtB = new javax.swing.JLabel();
        txtC = new javax.swing.JLabel();
        txtD = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnTruoc = new javax.swing.JButton();
        btnTiep = new javax.swing.JButton();
        btnGui = new javax.swing.JButton();
        txtsec = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txttic = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList);

        jLabel1.setText("Câu");

        txtCauSoMay.setText("40");

        txtCauHoi.setText("Câu hỏi");

        buttonGroup1.add(btnA);
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnB);
        btnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnC);
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnD);
        btnD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDActionPerformed(evt);
            }
        });

        txtA.setText("A");

        txtB.setText("B");

        txtC.setText("C");

        txtD.setText("D");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtD))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtC))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtB))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtA))
                    .addComponent(txtCauHoi)
                    .addComponent(txtCauSoMay))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtD)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCauSoMay))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtCauHoi)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnA))
                                            .addComponent(txtA))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnB))
                                    .addComponent(txtB))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnC))
                            .addComponent(txtC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnD)))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        btnTruoc.setText("Trước");
        btnTruoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruocActionPerformed(evt);
            }
        });

        btnTiep.setText("Tiếp");
        btnTiep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(btnTruoc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTiep)
                .addContainerGap(666, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTruoc)
                    .addComponent(btnTiep)))
        );

        btnGui.setText("Gửi");
        btnGui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiActionPerformed(evt);
            }
        });

        txtsec.setText("00");

        jLabel9.setText(":");

        txttic.setText("00");

        jLabel11.setText(":");

        txtmin.setText("00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGui, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtsec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttic)
                        .addGap(24, 24, 24)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsec)
                    .addComponent(jLabel9)
                    .addComponent(txttic)
                    .addComponent(jLabel11)
                    .addComponent(txtmin))
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGui))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
        // TODO add your handling code here:
        chon[tangGiam] = tangGiam + 1 + " - A";
        listModel.setElementAt(chon[tangGiam], tangGiam);
        jList.setModel(listModel);
        chonDapAn[tangGiam] = txtA.getText();
    }//GEN-LAST:event_btnAActionPerformed

    private void btnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBActionPerformed
        // TODO add your handling code here:
        chon[tangGiam] = tangGiam + 1 + " - B";
        listModel.setElementAt(chon[tangGiam], tangGiam);
        jList.setModel(listModel);
        chonDapAn[tangGiam] = txtB.getText();
    }//GEN-LAST:event_btnBActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        // TODO add your handling code here:
        chon[tangGiam] = tangGiam + 1 + " - C";
        listModel.setElementAt(chon[tangGiam], tangGiam);
        jList.setModel(listModel);
        chonDapAn[tangGiam] = txtC.getText();
    }//GEN-LAST:event_btnCActionPerformed

    private void btnDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDActionPerformed
        // TODO add your handling code here:
        chon[tangGiam] = tangGiam + 1 + " - D";
        listModel.setElementAt(chon[tangGiam], tangGiam);
        jList.setModel(listModel);
        chonDapAn[tangGiam] = txtD.getText();
    }//GEN-LAST:event_btnDActionPerformed

    private void btnTruocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruocActionPerformed
        // TODO add your handling code here:
        if (tangGiam >= 1 && tangGiam <list.size()) {
            tangGiam--;
            lamBai();
        }
    }//GEN-LAST:event_btnTruocActionPerformed

    private void btnTiepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiepActionPerformed
        // TODO add your handling code here:
        if (tangGiam >= 0 && tangGiam <(list.size() - 1)) {
            tangGiam++;
            lamBai();
        }
    }//GEN-LAST:event_btnTiepActionPerformed

    private void btnGuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuiActionPerformed

    private void jListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListValueChanged
        // TODO add your handling code here:
        lamBai();
    }//GEN-LAST:event_jListValueChanged

    /**
     * @param args the command line arguments
     */
    public void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LamBai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LamBai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LamBai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LamBai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LamBai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnA;
    private javax.swing.JRadioButton btnB;
    private javax.swing.JRadioButton btnC;
    private javax.swing.JRadioButton btnD;
    private javax.swing.JButton btnGui;
    private javax.swing.JButton btnTiep;
    private javax.swing.JButton btnTruoc;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtA;
    private javax.swing.JLabel txtB;
    private javax.swing.JLabel txtC;
    private javax.swing.JLabel txtCauHoi;
    private javax.swing.JLabel txtCauSoMay;
    private javax.swing.JLabel txtD;
    private javax.swing.JLabel txtmin;
    private javax.swing.JLabel txtsec;
    private javax.swing.JLabel txttic;
    // End of variables declaration//GEN-END:variables
}
